[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "man"
version = "0.1.0"
description = "Universal Manual Reader"
requires-python = ">=3.9"
dependencies = [
    "rich"
]

[project.scripts]
man = "man.cli:main"

[tool.setuptools]
packages = ["man"]
